import grpc
import logging
import asyncio
from typing import Callable, Dict

# Generated by protoc (you would include these in your library)
import swarm_pb2
import swarm_pb2_grpc

class DroneClient:
    def __init__(self, drone_id: str, server_address: str = 'localhost:50051'):
        self.drone_id = drone_id
        self.server_address = server_address
        self._command_handlers: Dict[str, Callable] = {}
        self._channel = None
        self._stub = None
        self.is_running = False

    def on_command(self, command_name: str):
        """
        Decorator to register a function to handle a specific server command.
        Example:
        @drone.on_command("TAKEOFF")
        async def handle_takeoff(params): ...
        """
        def decorator(func):
            self._command_handlers[command_name] = func
            return func
        return decorator

    async def connect(self):
        """Establishes gRPC channel and starts the command loop."""
        self._channel = grpc.aio.insecure_channel(self.server_address)
        self._stub = swarm_pb2_grpc.DroneHubStub(self._channel)
        self.is_running = True
        print(f"[{self.drone_id}] Connected to Hive at {self.server_address}")

        # Start the listener loop
        await self._listen_for_commands()

    async def _listen_for_commands(self):
        """Internal loop to consume the gRPC stream from the .NET server."""
        identity = swarm_pb2.DroneIdentity(drone_id=self.drone_id, swarm_group="Alpha")
        
        try:
            # This is a blocking stream that waits for server messages
            async for command in self._stub.ConnectToHive(identity):
                cmd_name = command.command_name
                params = command.parameters
                
                if cmd_name in self._command_handlers:
                    print(f"[{self.drone_id}] Received command: {cmd_name}")
                    # Execute the registered handler asynchronously
                    asyncio.create_task(self._command_handlers[cmd_name](params))
                else:
                    print(f"[{self.drone_id}] Warning: No handler for {cmd_name}")
                    
        except grpc.RpcError as e:
            print(f"Disconnected: {e}")

    async def send_telemetry(self, battery: float, status: str):
        """Utility to push data back to .NET server."""
        # Implementation of telemetry stream would go here
        pass